apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80         # External Port
      targetPort: 8080 # Internal Port (matches containerPort)
  type: LoadBalancer   # Exposes service externally (use NodePort for local testing)
